// <auto-generated />
namespace PatternCreator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class YOUR_FIRST_MIGRATION : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YOUR_FIRST_MIGRATION));
        
        string IMigrationMetadata.Id
        {
            get { return "202001301248295_YOUR_FIRST_MIGRATION"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
